### PR TITLE
Update ruby in root fs to p545

### PR DESCRIPTION
**Pull request by sykesm**
- Update .ruby-version for version managers
- Use p545 instead of p392 in /usr/local

[#71367862]

Signed-off-by: Michael Fraenkel fraenkel@us.ibm.com

### CODE REVIEW

**Comment by mkocher** [comment]
Changes to the rootfs scare me. Are we sure this won't break old droplets?

**Comment by sykesm** [comment]
@mkocher, the short answer is 'no.'

There was a discussion at IPM and the consensus was that the ruby in the root fs was mostly used to host the buildpacks and that apps which were staged through the ruby buildpack would carry the ruby provisioned for them by the buildpack.  Applications that were staged through other means may be using the ruby from the root fs.

The root fs was explicitly called out in the referenced [story](https://www.pivotaltracker.com/story/show/71367862) so that's where this update is coming from.  Sounds like it warrants more discussion.

**Comment by mkocher** [comment]
Apologies for not being clear, I wasn't saying don't do this, I just wanted to make sure we'd considered the risks.

:thumbsup:

**Comment by mkocher** [comment]
Also, has runtime considered standardizing on the Diego docker approach to building the rootfs?

I'm not sure if there's a reason to maintain both at this point.

/cc @vito

**Comment by fraenkel** [comment]
We can apply the changes to the docker branch as well.
Shouldn't the docker branch just become master if thats the direction?

**Pull request merged**
